# Generated by Django 4.2.8 on 2023-12-25 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lvl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_required', models.IntegerField(default=50)),
                ('exp_current', models.IntegerField(default=0)),
                ('lvl_current', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Party5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.lvl')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('nickname', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('party5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Party5', to='Api.party5')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='party5',
            name='fifth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifth', to='Api.slot'),
        ),
        migrations.AddField(
            model_name='party5',
            name='first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to='Api.slot'),
        ),
        migrations.AddField(
            model_name='party5',
            name='fourth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth', to='Api.slot'),
        ),
        migrations.AddField(
            model_name='party5',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='Api.slot'),
        ),
        migrations.AddField(
            model_name='party5',
            name='third',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='Api.slot'),
        ),
    ]
