# Generated by Django 4.2.8 on 2023-12-25 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_player_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='party5',
            name='nickname',
            field=models.ForeignKey(default='sad', on_delete=django.db.models.deletion.CASCADE, related_name='Party5_nick', to='Api.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party5',
            name='fifth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth', to='Api.slot'),
        ),
        migrations.AlterField(
            model_name='party5',
            name='first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='Api.slot'),
        ),
        migrations.AlterField(
            model_name='party5',
            name='fourth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth', to='Api.slot'),
        ),
        migrations.AlterField(
            model_name='party5',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='Api.slot'),
        ),
        migrations.AlterField(
            model_name='party5',
            name='third',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='Api.slot'),
        ),
    ]
