# Generated by Django 4.2.8 on 2023-12-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_party5_nickname_alter_party5_fifth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='party5',
        ),
    ]
